<?php

use Illuminate\Database\Migrations\Migration;
use Illuminate\Database\Schema\Blueprint;
use Illuminate\Support\Facades\Schema;

class AddOthersToEmployeesTable extends Migration
{
    /**
     * Run the migrations.
     *
     * @return void
     */
    public function up()
    {
        Schema::table('employees', function (Blueprint $table) {
            $table->string('EmployeeID')->nullable();
            $table->string('FirstName')->nullable();
            $table->string('MiddleName')->nullable();
            $table->string('LastName')->nullable();
            $table->foreignId('branches_id')->default(1)->constrained();
            $table->foreignId('departments_id')->default(1)->constrained();
            $table->foreignId('positions_id')->default(1)->constrained();
            $table->foreignId('salaries_id')->default(2)->constrained();
            $table->foreignId('employementtypes_id')->default(1)->constrained();
            $table->foreignId('employees_id')->default(1)->constrained();
            $table->string('HiredDate')->nullable();
            $table->string('Tin')->nullable();
            $table->string('Dob')->nullable();
            $table->string('Gender')->nullable();
            $table->string('ResidanceIdNumber')->nullable();
            $table->string('NationalIdNumber')->nullable();
            $table->string('PassportNumber')->nullable();
            $table->string('Email')->nullable();
            $table->string('MobileNumber')->nullable();
            $table->string('OfficePhoneNumber')->nullable();
            $table->string('Postcode')->nullable();
            $table->string('DrivingLicenseNumber')->nullable();
            $table->string('Address')->nullable();
            $table->string('Nationality')->nullable();
            $table->string('MartialStatus')->nullable();
            $table->string('Country')->nullable();
            $table->integer('cities_id')->nullable()->default(0);
            $table->integer('subcities_id')->nullable()->default(0);
            $table->string('Woreda')->nullable();
            $table->string('EmergencyName')->nullable();
            $table->string('EmergencyPhone')->nullable();
            $table->string('EmergencyAddress')->nullable();
            $table->string('EnableAttendance')->nullable();
            $table->string('EnableHoliday')->nullable();
            $table->string('AccessStatus')->nullable();
            $table->integer('AccessRole')->nullable()->default(0);
            $table->foreignId('banks_id')->default(1)->constrained();
            $table->string('PaymentPeriond')->nullable();
            $table->string('PaymentType')->nullable();
            $table->string('BankAccountNumber')->nullable();
            $table->string('PensionNumber')->nullable();
            $table->string('ProvidentFundAccount')->nullable();
            $table->double('BasicSalary')->nullable()->default(0);
            $table->double('NetSalary')->nullable()->default(0);
            $table->double('MedicalAllowance')->nullable()->default(0);
            $table->double('HomeRentAllowance')->nullable()->default(0);
            $table->double('TransportAllowance')->nullable()->default(0);
            $table->double('Bonus')->nullable()->default(0);
            $table->double('OtherEarning')->nullable()->default(0);
            $table->double('Tax')->nullable()->default(0);
            $table->double('ProvidentFund')->nullable()->default(0);
            $table->double('Loan')->nullable()->default(0);
            $table->double('CostSharingDeduction')->nullable()->default(0);
            $table->double('OtherDeduction')->nullable()->default(0);
            $table->integer('UpdateSalaryFlag')->nullable()->default(0);
            $table->string('ContractSignDate')->nullable();
            $table->string('RenewDate')->nullable();
            $table->string('ContractDuration')->nullable();
            $table->string('ResumeDocument')->nullable();
            $table->string('WorkExpDocument')->nullable();
            $table->string('AwardDocument')->nullable();
            $table->string('TrainingDocument')->nullable();
            $table->string('RecommendationDocument')->nullable();
            $table->string('OtherDocument')->nullable();
            $table->foreignId('devices_id')->default(2)->constrained();
            $table->string('PIN')->nullable();
            $table->string('CardNumber')->nullable();
            $table->string('ActualPicture')->nullable();
            $table->string('BiometricPicture')->nullable();
            $table->longtext('LeftThumb')->nullable();
            $table->longtext('LeftIndex')->nullable();
            $table->longtext('LeftMiddle')->nullable();
            $table->longtext('LeftRing')->nullable();
            $table->longtext('LeftPinky')->nullable();
            $table->longtext('RightThumb')->nullable();
            $table->longtext('RightIndex')->nullable();
            $table->longtext('RightMiddle')->nullable();
            $table->longtext('RightRing')->nullable();
            $table->longtext('RightPinky')->nullable();
            $table->string('GeneralMemo',"65535")->nullable();
            $table->string('PersonalMemo',"65535")->nullable();
            $table->string('EmergencyMemo',"65535")->nullable();
            $table->string('BiometricMemo',"65535")->nullable();
            $table->string('AttendanceMemo',"65535")->nullable();
            $table->string('AccessMemo',"65535")->nullable();
            $table->string('PayrollMemo',"65535")->nullable();
            $table->string('DocumentMemo',"65535")->nullable();
            $table->string('ContractMemo',"65535")->nullable();
            $table->integer('AnnualLeave')->nullable()->default(0);
            $table->integer('SickLeave')->nullable()->default(0);
            $table->integer('MaternityLeave')->nullable()->default(0);
            $table->integer('PaternityLeave')->nullable()->default(0);
            $table->integer('CasualLeave')->nullable()->default(0);
            $table->integer('BereavementLeave')->nullable()->default(0);
            $table->integer('CompensatoryLeave')->nullable()->default(0);
            $table->integer('UnpaidLeave')->nullable()->default(0);
            $table->integer('LeaveA')->nullable()->default(0);
            $table->integer('LeaveB')->nullable()->default(0);
            $table->integer('LeaveC')->nullable()->default(0);
            $table->string('CreatedBy')->nullable();
            $table->string('CreatedDate')->nullable();
            $table->string('LastEditedBy')->nullable();
            $table->string('LastEditedDate')->nullable();
            $table->string('Status',100)->nullable();
        });
    }

    /**
     * Reverse the migrations.
     *
     * @return void
     */
    public function down()
    {
        Schema::table('employees', function (Blueprint $table) {
            //
            $table->dropColumn('EmployeeID');
            $table->dropColumn('FirstName');
            $table->dropColumn('MiddleName');
            $table->dropColumn('LastName');
            $table->dropColumn('branches_id');
            $table->dropColumn('departments_id');
            $table->dropColumn('positions_id');
            $table->dropColumn('salaries_id');
            $table->dropColumn('employementtypes_id');
            $table->dropColumn('employees_id');
            $table->dropColumn('HiredDate');
            $table->dropColumn('Tin');
            $table->dropColumn('Dob');
            $table->dropColumn('Gender');
            $table->dropColumn('ResidanceIdNumber');
            $table->dropColumn('NationalIdNumber');
            $table->dropColumn('PassportNumber');
            $table->dropColumn('Email');
            $table->dropColumn('MobileNumber');
            $table->dropColumn('OfficePhoneNumber');
			$table->dropColumn('Postcode');
			$table->dropColumn('DrivingLicenseNumber');
			$table->dropColumn('Address');
			$table->dropColumn('Nationality');
			$table->dropColumn('MartialStatus');
			$table->dropColumn('Country');
			$table->dropColumn('cities_id');
			$table->dropColumn('subcities_id');
			$table->dropColumn('Woreda');
			$table->dropColumn('EmergencyName');
			$table->dropColumn('EmergencyPhone');
			$table->dropColumn('EmergencyAddress');
			$table->dropColumn('EnableAttendance');
			$table->dropColumn('EnableHoliday');
			$table->dropColumn('AccessStatus');
			$table->dropColumn('AccessRole');
			$table->dropColumn('banks_id');
			$table->dropColumn('PaymentPeriond');
			$table->dropColumn('PaymentType');
			$table->dropColumn('BankAccountNumber');
			$table->dropColumn('PensionNumber');
			$table->dropColumn('ProvidentFundAccount');
			$table->dropColumn('BasicSalary');
			$table->dropColumn('NetSalary');
			$table->dropColumn('MedicalAllowance');
			$table->dropColumn('HomeRentAllowance');
			$table->dropColumn('TransportAllowance');
			$table->dropColumn('Bonus');
			$table->dropColumn('OtherEarning');
			$table->dropColumn('Tax');
			$table->dropColumn('ProvidentFund');
			$table->dropColumn('Loan');
			$table->dropColumn('CostSharingDeduction');
			$table->dropColumn('OtherDeduction');
			$table->dropColumn('UpdateSalaryFlag');
			$table->dropColumn('ContractSignDate');
			$table->dropColumn('RenewDate');
            $table->dropColumn('ContractDuration');
			$table->dropColumn('ResumeDocument');
			$table->dropColumn('WorkExpDocument');
			$table->dropColumn('AwardDocument');
			$table->dropColumn('TrainingDocument');
			$table->dropColumn('RecommendationDocument');
			$table->dropColumn('OtherDocument');
			$table->dropColumn('devices_id');
			$table->dropColumn('PIN');
			$table->dropColumn('CardNumber');
			$table->dropColumn('Picture');
			$table->dropColumn('LeftThumb');
            $table->dropColumn('LeftIndex');
            $table->dropColumn('LeftMiddle');
            $table->dropColumn('LeftRing');
            $table->dropColumn('LeftPinky');
            $table->dropColumn('RightThumb');
            $table->dropColumn('RightIndex');
            $table->dropColumn('RightMiddle');
            $table->dropColumn('RightRing');
            $table->dropColumn('RightPinky');
			$table->dropColumn('GeneralMemo');
			$table->dropColumn('PersonalMemo');
			$table->dropColumn('EmergencyMemo');
			$table->dropColumn('BiometricMemo');
			$table->dropColumn('AttendanceMemo');
			$table->dropColumn('AccessMemo');
			$table->dropColumn('PayrollMemo');
			$table->dropColumn('DocumentMemo');
            $table->dropColumn('ContractMemo');
            $table->dropColumn('AnnualLeave');
            $table->dropColumn('SickLeave');
            $table->dropColumn('MaternityLeave');
            $table->dropColumn('PaternityLeave');
            $table->dropColumn('CasualLeave');
            $table->dropColumn('BereavementLeave');
            $table->dropColumn('CompensatoryLeave');
            $table->dropColumn('UnpaidLeave');
            $table->dropColumn('LeaveA');
            $table->dropColumn('LeaveB');
            $table->dropColumn('LeaveC');
			$table->dropColumn('CreatedBy');
			$table->dropColumn('CreatedDate');
			$table->dropColumn('LastEditedBy');
			$table->dropColumn('LastEditedDate');
			$table->dropColumn('Status');
        });
    }
}
